# Generated by Django 4.1.7 on 2023-05-01 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('date_aj', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-date_aj'],
            },
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150)),
                ('prx', models.FloatField()),
                ('description', models.TextField()),
                ('image', models.CharField(max_length=4000)),
                ('date_aj', models.DateTimeField(auto_now=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categorie', to='our_shop.categorie')),
            ],
            options={
                'ordering': ['-date_aj'],
            },
        ),
    ]
