# Generated by Django 4.2 on 2023-05-05 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('our_shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=300)),
                ('nom', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=90)),
                ('ville', models.CharField(max_length=110)),
                ('pays', models.CharField(max_length=200)),
                ('date_Commande', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
