# Generated by Django 4.2.1 on 2023-05-05 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('our_shop', '0002_commande'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commande',
            options={'ordering': ['-date_commande']},
        ),
        migrations.RenameField(
            model_name='commande',
            old_name='date_Commande',
            new_name='date_commande',
        ),
    ]
